# Usuario con el que se ejecuta NGINX (no root)
user www-data;

# Workers automáticos según CPU disponible
worker_processes auto;

# PID del proceso principal
pid /run/nginx.pid;

events {
    # Máximo de conexiones simultáneas por worker
    worker_connections 1024;
}

http {
    # Tipos MIME conocidos
    include       mime.types;
    default_type  application/octet-stream;

    # Activar sendfile para optimizar envío de archivos
    sendfile        on;

    # Mantener conexiones activas
    keepalive_timeout 65;

        # No mostrar versión de nginx
    server_tokens off;

    # Logs hacia Docker
    access_log /dev/stdout;
    error_log  /dev/stderr;

    # Incluir virtual hosts
    include /etc/nginx/conf.d/*.conf;
}


# Configuración global de NGINX.
# Define usuario seguro, workers y conexiones.
# Incluye todos los virtual hosts desde conf.d/.