; ========================================
; Pool de procesos PHP-FPM para WordPress
; ========================================

[www]  ; Nombre del pool

; ----------------------------------------
; Usuario y grupo que ejecutarán los procesos PHP
; ----------------------------------------
user = www-data
group = www-data

; ----------------------------------------
; Dirección y puerto donde PHP-FPM escuchará
; TCP 0.0.0.0:9000 permite que Nginx en otro contenedor se conecte
; ----------------------------------------
listen = 0.0.0.0:9000
# Usar listen = 0.0.0.0:9000 es obligatorio en Docker cuando NGINX está en otro contenedor

; ----------------------------------------
; Permisos del socket si se usara Unix socket (opcional con TCP)
; ----------------------------------------
listen.owner = www-data
listen.group = www-data


# Configuración del gestor de procesos (pm)
# pm significa Process Manager, es un gestor de procesos
# dynamic es un tipo de procesos, este ajusta número de procesos según carga

pm = dynamic              ; dynamic no consume recursos de más
pm.max_children = 5       ; Máximo de procesos PHP simultáneos
pm.start_servers = 2      ; Número de procesos al iniciar FPM
pm.min_spare_servers = 1  ; Mínimo de procesos inactivos listos para peticiones
pm.max_spare_servers = 3  ; Máximo de procesos inactivos

; ----------------------------------------
; Redirigir stdout y stderr de los procesos PHP al log principal
; Permite que docker logs muestre errores de PHP. Muy útil para depuración
; ----------------------------------------
catch_workers_output = yes